// <auto-generated />
using System;
using HntdApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HntdApi.Migrations
{
    [DbContext(typeof(HntdApiDbContext))]
    [Migration("20251130211310_AddIdentity")]
    partial class AddIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HntdApi.Models.ActivityLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ActivityLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Occasional unexplained occurrences",
                            Name = "Mild"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Regular paranormal activity reported",
                            Name = "Moderate"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Frequent and intense activity",
                            Name = "High"
                        });
                });

            modelBuilder.Entity("HntdApi.Models.HauntedLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityLevelId")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("History")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<int>("LocationTypeId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActivityLevelId");

                    b.HasIndex("LocationTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("HauntedLocations");
                });

            modelBuilder.Entity("HntdApi.Models.LocationActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HauntedLocationId")
                        .HasColumnType("integer");

                    b.Property<int>("ParanormalActivityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HauntedLocationId");

                    b.HasIndex("ParanormalActivityId");

                    b.ToTable("LocationActivities");
                });

            modelBuilder.Entity("HntdApi.Models.LocationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LocationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cemetery"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hospital"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Asylum"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Prison"
                        },
                        new
                        {
                            Id = 5,
                            Name = "House"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Hotel"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Battlefield"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Church"
                        });
                });

            modelBuilder.Entity("HntdApi.Models.ParanormalActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("IconName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ParanormalActivities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Visual ghost sightings",
                            IconName = "ghost",
                            Name = "Apparitions"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Electronic voice phenomena",
                            IconName = "mic",
                            Name = "EVP"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Unexplained temperature drops",
                            IconName = "thermometer",
                            Name = "Cold Spots"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Items moving on their own",
                            IconName = "move",
                            Name = "Object Movement"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Dark humanoid shapes",
                            IconName = "shadow",
                            Name = "Shadow Figures"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Voices heard without source",
                            IconName = "volume",
                            Name = "Disembodied Voices"
                        });
                });

            modelBuilder.Entity("HntdApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("HntdApi.Models.UserFavorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HauntedLocationId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HauntedLocationId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFavorites");
                });

            modelBuilder.Entity("HntdApi.Models.HauntedLocation", b =>
                {
                    b.HasOne("HntdApi.Models.ActivityLevel", "ActivityLevel")
                        .WithMany()
                        .HasForeignKey("ActivityLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HntdApi.Models.LocationType", "LocationType")
                        .WithMany()
                        .HasForeignKey("LocationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HntdApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityLevel");

                    b.Navigation("LocationType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HntdApi.Models.LocationActivity", b =>
                {
                    b.HasOne("HntdApi.Models.HauntedLocation", "HauntedLocation")
                        .WithMany()
                        .HasForeignKey("HauntedLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HntdApi.Models.ParanormalActivity", "ParanormalActivity")
                        .WithMany()
                        .HasForeignKey("ParanormalActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HauntedLocation");

                    b.Navigation("ParanormalActivity");
                });

            modelBuilder.Entity("HntdApi.Models.UserFavorite", b =>
                {
                    b.HasOne("HntdApi.Models.HauntedLocation", "HauntedLocation")
                        .WithMany()
                        .HasForeignKey("HauntedLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HntdApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HauntedLocation");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
